name: Execute private action 
description: Execute a private composite action 
branding:
  icon: download
  color: blue
inputs:
  #u: 
  #  description: The private repository org/repo@ref
  #  required: true
  repository:
    description: org/repo
    required: true
  ref: 
    description: Branch, tag, or commit to checkout if not default branch
    required: false
  ssh-key:
    description: A GitHub Deploy key, an SSH private key, to access to clone the private repository
    required: false
  token:
    description: A GitHub App Installation token, or a personal access token (not recommended)
    required: false
  
runs:
  using: composite
  steps: 
  - name: Get the ref
    shell: bash
    id: checkout
    env: 
      PRIVATE_ACTION_REPO_AND_REF: ${{ inputs.repository }}
    run: |
      echo "GITHUB_ACTION_PATH="$GITHUB_ACTION_PATH
      export PRIVATE_ACTION_REF=`echo $PRIVATE_ACTION_REPO_AND_REF | sed 's/@/ @ /' | awk '{print $3}'`
      export PRIVATE_ACTION_ORG_REPO=`echo $PRIVATE_ACTION_REPO_AND_REF | sed 's/@/ @ /' | awk '{print $1}'`
      export PRIVATE_ACTION_REPO=`echo $PRIVATE_ACTION_ORG_REPO | sed 's/\// \/ /' | awk '{print $3}'`
      echo '::set-output name=ref::'$PRIVATE_ACTION_REF
      echo '::set-output name=repo::'$PRIVATE_ACTION_ORG_REPO
      echo '::set-output name=action_path::'$PRIVATE_ACTION_REPO
      echo "PRIVATE_ACTION_PATH=./$PRIVATE_ACTION_REPO" >> $GITHUB_ENV
  - name: Clone and checkout private action
    uses: actions/checkout@v3
    with:
      ssh-key: ${{ inputs.ssh-key }}
      repository: ${{ steps.checkout.outputs.repo }}
      path: ${{ steps.checkout.outputs.action_path }}
      ref: ${{ steps.checkout.outputs.ref }}
  - name: Execute the private action in ${{ env.PRIVATE_ACTION_PATH }}
    uses: ./hello-world-private-action
   # uses: ${{ env.PRIVATE_ACTION_PATH }}
    #with:

